services:
    app-sumo:
        image: app_sumo

        networks:
            - scrape-net

    product-hunt:
        image: product_hunt

        networks:
          - scrape-net
        
      
    saas-worthy:
        image: saas_worthy
        
        networks:
          - scrape-net
        
    g2-consumer:
        image: g2_consumer

        networks:
          - scrape-net
        
        

        depends_on: [app-sumo,saas-worthy, product-hunt]


networks:
  scrape-net:
    external: true